### ISSUE TITLE
Discord Invite

### ISSUE THREAD

**Issue by erunks** [speedrun-website/speedrun-infosite#1]
Just a heads up, the discord Invite on the main page has expired. Probably gonna want to swap it out with one that never expires, unless this was intentional.

**Comment by ZacharyTalis** [comment]
Oh shoot, I'll get that fixed right away!

...I gotta wait for my ssh permissions to be restored because I made a dumb mistake, but once that happens we'll be good to go.

**Comment by erunks** [comment]
Looks like this was fixed in this commit: https://github.com/speedrun-website/speedrun-infosite/commit/3e6d8b8379d0b906926b9e4527a8c43898ce552e. Gonna close out the issue 👍

**Comment by ZacharyTalis** [comment]
Oh I was planning on closing the issue once I had updated the actual site, not just the repo. In any case, I'll tackle that once I snag some SSH access.

**Comment by ZacharyTalis** [comment]
Update: it's fixed now! <3
